version: '3.8'


services:
    web:
        build: ./app 
        command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000    
        #command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - static_volume:/usr/src/app/static
            - media_volume:/usr/src/app/media
        #ports:
            #- 8000:8000 
        expose:
            - 8000
        env_file:
            - ./.env.dev
        networks:
            - my_net
        depends_on:
            - db
   
    db:
        image: "postgres:latest"
        
        volumes:
            - postgres_volume:/var/lib/postgresql/data/
        env_file:
            - ./.env.dev
            #- ./logs:/var/logs
            #- .:/docker-entrypoint-initdb.db
            #- pgdata: /var/lib/podtgresql/data
        networks:
            - my_net 

            
    nginx:
        build: ./nginx
        ports:
            - 8080:80
        volumes:
            - static_volume:/usr/src/app/static
            - media_volume:/usr/src/app/media
        depends_on:
            - web
        networks:
            - my_net 
volumes:
    postgres_volume: 
    static_volume:
    media_volume:
    
networks:
    my_net: